return {
  get_ast_context = require("src.lua.get-ast-context"),
  goto_definition = require("src.lua.goto-definition"),
  -- diagnostics = require("src.lua.diagnostics"),
  get_document_symbols = require("src.lua.get-document-symbols"),
  -- get_quickfix = require("src.lua.get-quickfix"),
  -- hover = require("src.lua.hover"),
  -- implementation = require("src.lua.implementation"),
  -- index = require("src.lua.index"),
  -- references = require("src.lua.references"),
  restart_lsp = require("src.lua.restart-lsp"),
  -- set_quickfix = require("src.lua.set-quickfix"),
  -- utils = require("src.lua.utils"),
  workspace_symbols = require("src.lua.workspace-symbols"),
}
