return {
  get_ast_context = require("src.lua.get-ast-context"),
  goto_definition = require("src.lua.goto-definition"),
  get_diagnostics = require("src.lua.get-diagnostics"),
  get_document_symbols = require("src.lua.get-document-symbols"),
  workspace_symbols = require("src.lua.workspace-symbols"),
  hover = require("src.lua.hover"),
  goto_implementation = require("src.lua.goto-implementation"),
  get_references = require("src.lua.get-references"),
  restart_lsp = require("src.lua.restart-lsp"),
  -- start_lsp = require("src.lua.start-lsp"),
  get_lsp = require("src.lua.get-lsp"),
  get_quickfix = require("src.lua.get-quickfix"),
  set_quickfix = require("src.lua.set-quickfix"),
}
